# Generated by Django 5.1.5 on 2025-04-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile-pic-placeholder.png', null=True, upload_to=''),
        ),
    ]
