# Generated by Django 5.2 on 2025-04-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classes',
            field=models.ManyToManyField(blank=True, to='base.classes'),
        ),
    ]
