# Generated by Django 5.2 on 2025-04-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_currentskills_user_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='currentSkills',
            new_name='curretYear',
        ),
    ]
