# Generated by Django 5.2 on 2025-04-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_currentskills_user_curretyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curretYear',
            new_name='currentYear',
        ),
    ]
