# Generated by Django 5.1.5 on 2025-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_curretyear_user_currentyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
