# Generated by Django 5.1.5 on 2025-04-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tutor',
        ),
    ]
