# Generated by Django 5.1.5 on 2025-04-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_user_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutor',
            field=models.BooleanField(default=False),
        ),
    ]
