# Generated by Django 5.1.6 on 2025-04-30 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default='Add a comment!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'tutor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Tutors', to=settings.AUTH_USER_MODEL),
        ),
    ]
