# Generated by Django 5.1.5 on 2025-04-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_review_student_alter_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-rating']},
        ),
    ]
